export const ORU_PID_DEFINETION = {
  setID: 'PID.1',
  patientID: 'PID.2',
  patientIdentifierList: {
    idNumber: 'PID.3.1',
    identifierTypeCode: 'PID.3.5',
    assigningAuthority: 'PID.3.4',
  },
  alternatePatientID: 'PID.4',
  patientName: {
    familyName: 'PID.5.1',
    givenName: 'PID.5.2',
    middleName: 'PID.5.3',
    suffix: 'PID.5.4',
    prefix: 'PID.5.5',
    degree: 'PID.5.6',
  },
  mothersMaidenName: 'PID.6',
  dateTimeOfBirth: 'PID.7',
  administrativeSex: 'PID.8',
  patientAlias: 'PID.9',
  race: {
    identifier: 'PID.10.1',
    text: 'PID.10.2',
    nameOfCodingSystem: 'PID.10.3',
    alternateIdentifier: 'PID.10.4',
    alternateText: 'PID.10.5',
    nameOfAlternateCodingSystem: 'PID.10.6',
  },
  patientAddress: {
    streetAddress: 'PID.11.1',
    otherDesignation: 'PID.11.2',
    city: 'PID.11.3',
    stateOrProvince: 'PID.11.4',
    zipOrPostalCode: 'PID.11.5',
    country: 'PID.11.6',
    addressType: 'PID.11.7',
  },
  phoneNumberHome: {
    telephoneNumber: 'PID.13.1',
    emailAddress: 'PID.13.4',
    countryCode: 'PID.13.7',
    areaCityCode: 'PID.13.8',
    localNumber: 'PID.13.9',
    extension: 'PID.13.10',
    anyText: 'PID.13.11',
    extensionPrefix: 'PID.13.12',
  },
  phoneNumberBusiness: {
    telephoneNumber: 'PID.14.1',
    emailAddress: 'PID.14.4',
    countryCode: 'PID.14.7',
    areaCityCode: 'PID.14.8',
    localNumber: 'PID.14.9',
    extension: 'PID.14.10',
    anyText: 'PID.14.11',
    extensionPrefix: 'PID.14.12',
  },
  primaryLanguage: 'PID.15',
  maritalStatus: 'PID.16',
  religion: 'PID.17',
  patientAccountNumber: 'PID.18',
  ssnNumberPatient: 'PID.19',
  driversLicenseNumberPatient: 'PID.20',
  mothersIdentifier: 'PID.21',
  ethnicGroup: 'PID.22',
  birthPlace: 'PID.23',
  multipleBirthIndicator: 'PID.24',
  birthOrder: 'PID.25',
  citizenship: 'PID.26',
  veteransMilitaryStatus: 'PID.27',
  nationality: 'PID.28',
  patientDeathDateAndTime: 'PID.29',
  patientDeathIndicator: 'PID.30',
  identityUnknownIndicator: 'PID.31',
  identityReliabilityCode: 'PID.32',
  lastUpdateDateTime: 'PID.33',
  lastUpdateFacility: 'PID.34',
  speciesCode: 'PID.35',
  breedCode: 'PID.36',
  strain: 'PID.37',
  productionClassCode: 'PID.38',
  tribalCitizenship: 'PID.39',
  patientTelecommunicationInformation: 'PID.40',
};
